name: Cypress api tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        browser: chrome